export const LANDSCAPE = 'LANDSCAPE';
export const BIRD = 'BIRD';
export const MAMMAL = 'MAMMAL';
export const FISH = 'FISH';
export const REPTAMPH = 'REPTAMPH'; // reptile/amphibian
export const BUTTERFLY = 'BUTTERFLY';
export const INSECT = 'INSECT';
export const ARACHNID = 'ARACHNID';
export const FLOWER = 'FLOWER';
export const PLANT = 'PLANT';
export const TREE = 'TREE';
export const MUSHROOM = 'MUSHROOM';
export const WEATHER = 'WEATHER';
export const OTHER = 'OTHER';
